import { defineLevel } from './utils';
import { Music } from '../utils/assetUtils';
export default defineLevel({
  name: 'Baby Monkey\'s Tree House',
  backgroundColor: '#333333',
  song: Music.SONG1,
  startX: 3,
  startY: 3,
  tileData: [
    'ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
    'g          g                                                                  g',
    'g          g   b                                                              g',
    'g          g                                                                  g',
    'g          gggggggg                                                           g',
    'g                                                                             g',
    'g          gggg  ggggg                                                        g',
    'g          g         g                                                        g',
    'gggggggggggg         g                                                        g',
    'g                    g                                                        g',
    'g               b    g                                                        g',
    'g                    g                                                        g',
    'g                    g                                                        g',
    'g  ggggggggggggggggggg                                                        g',
    'g                                                                             g',
    'g                                                                             g',
    'g                                                                             g',
    'g          s                                                                  g',
    'g                                                                             g',
    'g       s                b                                                    g',
    'g                                                                             g',
    'g         s                                                                   g',
    'g    sss                                                                      g',
    'g             s                                                               g',
    'g            b                                                                g',
    'g       sss                                                                   g',
    'g                    b                                                        g',
    'ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  ],
});
