import { defineLevel } from './utils';
import { Music } from '../utils/assetUtils';
export default defineLevel({
  name: 'Baby Monkey\'s Tree House',
  backgroundColor: '#666666',
  song: Music.SONG1,
  startX: 3,
  startY: 3,
  tileData: [
    'ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
    'g          g            g                 s                                   g',
    'g          g   b        g                 s                                   g',
    'g          g                              s                                   g',
    'g          gggggggggggggg                 s         b                         g',
    'g                                         s           b                       g',
    'g          gggg  ggggg                    s                                   g',
    'g          g         g                    s                 b                 g',
    'gggggggggggg         g                                                        g',
    'g                    g                    s                                   g',
    'g               b    gsssssssssssssssssssssssssssssssssssss       ssssssssssssg',
    'g                    g                                    g       g           g',
    'g                    g                                    s       s           g',
    'g  ggggggggggggggggggg                                    g       g           g',
    'g              s                                          s       s           g',
    'g              s                                          g       g           g',
    'g              s                                          s       s           g',
    'g          s   s                                          g       g     b     g',
    'g              s                                                              g',
    'g       s      s         b                                                    g',
    'g              s                                   g                 gg       g',
    'g         s    ssssssssssssssssssss     s                   b                 g',
    'g    sss         b                      s               g       g             g',
    'g             s                         s                                     g',
    'g    b       b                          s                                     g',
    'g       sss                             s                   g                 g',
    'g                    b                  s                                     g',
    'ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  ],
});
